# This workflow will build a Java project with Ant
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-ant

name: Java CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    # steps:
    # - uses: actions/checkout@v4
    # - name: Set up JDK 22
    #   uses: actions/setup-java@v4
    #   with:
    #     java-version: '22'
    #     distribution: 'temurin'
    # - name: Build with Ant
    #   run: ant -noinput -buildfile build.xml

    # steps:
    #   - uses: actions/checkout@v4
    #   - uses: actions/setup-java@v4
    #     with:
    #       java-version: '22'
    #       distribution: 'temurin'
    
    #   - run: ant -noinput -buildfile build.xml
    #   - uses: actions/upload-artifact@v4
    #     with:
    #       name: Package
    #       path: build/jar

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
      - name: Run the Ant jar target
        run: ant -noinput -v -buildfile build.xml jar
      - name: Upload JAR file
        uses: actions/upload-artifact@v4
        with:
          name: output-jar
          path: dist/MachineProblem.jar  # Update this path based on the actual output

